#=============================================================================#
# General configuration                                                       #
#=============================================================================#

stages:
  - build
  - test
  - deploy

variables:
  MAVEN_OPTS: '-Dmaven.repo.local=.m2/repository'
  GIT_SUBMODULE_STRATEGY: 'normal'
  SWT_GTK3: '0'
  P2_ENABLE_COMPOSITE: '1'
  P2_COMPOSITE_NAME: 'SConsolidator'
  P2_ROOT_BASE: '/var/www/sconsolidator'
  P2_DESTINATION: 'P2_USE_REL_TAG'
  P2_SOURCE: './SconsolidatorProject/releng/ch.hsr.ifs.sconsolidator.update/target/repository'

#=============================================================================#
# Build jobs                                                                  #
#=============================================================================#

cache:
  key: 'maven-$CI_PROJECT_ID'
  paths:
    - '.m2/repository'
  policy: pull-push

Build Signed:
  image: gitlab.dev.ifs.hsr.ch:45023/cevelop/docker-tycho-release-with-scons:latest
  only:
    - master@cevelop/sconsolidator
    - develop@cevelop/sconsolidator
  stage: build
  script:
    - 'xvfb-run ./tools/build package -s'
  artifacts:
    expire_in: 1 hour
    paths:
      - './*/*/*/target/repository/**'

Build Unsigned:
  image: gitlab.dev.ifs.hsr.ch:45023/cevelop/docker-tycho-build-with-scons:latest
  only:
    - branches
  except:
    - master@cevelop/sconsolidator
    - develop@cevelop/sconsolidator
  stage: build
  script:
    - 'xvfb-run ./tools/build package'
  artifacts:
    expire_in: 1 hour
    paths:
      - './*/*/*/target/repository/**'

#=============================================================================#
# Test jobs                                                             #
#=============================================================================#
Test:
    image: gitlab.dev.ifs.hsr.ch:45023/cevelop/docker-tycho-build-with-scons:latest
    stage: test
    script:
      - 'xvfb-run ./tools/build verify -T 1C'
    dependencies: []
    artifacts:
      paths:
      - './*/tets/*/target/work/data/.metadata/.log'
      reports:
        junit: './*/tests/*/target/surefire-reports/TEST-*.xml'

#=============================================================================#
# Deployment jobs                                                             #
#=============================================================================#

Deploy:
  image: gitlab.dev.ifs.hsr.ch:45023/ifs/docker-alpine-ssh:latest
  cache: {}
  stage: deploy
  dependencies:
    - Build Signed
  only:
    - develop@cevelop/sconsolidator
    - master@cevelop/sconsolidator
  script:
    - "export P2_ROOT=${P2_ROOT_BASE}$( (echo ${CI_COMMIT_REF_NAME} | grep develop &>/dev/null) && echo '-unstable')"
    - "export P2_COMPOSITE_VERSION=$(sed -n 's/[ \\t]*<version>\\([0-9]\\.[0-9]\\.[0-9]\\)-SNAPSHOT<\\/version>/\\1/p' *Project/**/*.update/pom.xml | head -1)"
    - "./tools/ci/deploy"

